name: Build package-list

on:
  workflow_dispatch:

jobs:
  build-pkgs:
    runs-on: ubuntu-22.04
    steps:
      - uses: manjaro/manjaro-pkg-action@build_list
        with:
          gpg-key: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          boxit-host: ${{ secrets.BOXIT_HOST }}
          boxit-target: ${{ secrets.BOXIT_TARGET }}
          ssh-key: ${{ secrets.SSH_PACKAGE_CI }}
        
######### EDIT:
          package_list: xfce
          release_tag: 4.20-pre2
          ## path to source repo
          source_url: https://github.com/manjaro/xfce-4.20.git
          source_folder: xfce-4.20
          ## branch: (default: stable)
          branch: stable
          ## custom-repo - default: ""
          custom-repo: ""
